# Generated by Django 4.2 on 2023-05-02 06:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок задачи')),
                ('slug', models.SlugField(max_length=255, unique_for_date='publish', verbose_name='Ссылка на запись')),
                ('content', models.TextField(verbose_name='Контент задачи')),
                ('publish', models.DateTimeField(default=datetime.datetime(2023, 5, 2, 6, 0, 53, 111934, tzinfo=datetime.timezone.utc), verbose_name='Время публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задачи')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения задачи')),
                ('status', models.CharField(choices=[('опубликовано', 'Опубликовано'), ('неопубликовано', 'Неопубликовано')], default='опубликовано', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список дел',
                'ordering': ['-publish'],
            },
        ),
    ]
